// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntnlctvbixfyweofwoln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50bmxjdHZiaXhmeXdlb2Z3b2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODIxMTQsImV4cCI6MjA3NDY1ODExNH0.EVx0dOlKc667k3U_n_eF-jofbL_DRsi5Fq5tg5cznwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});